# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 80c18d1232cf0032f26278a9a050bd07c6047f15d71ad6679afdb58f0ad606d45d38ad9a5f72e8276e55fb3262f343b5eb7959930151bdf0236bedf793e0af3a

test:
  secret_key_base: 5d2ec5b30ece20d083c5decc30a96e4a435de84a521f169741d0de6b7f14c69c1226d4d0d3e5475318d32e73f238302b116a7e2dd05cbca9fa15b58e2c721c60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
